src/Entity/Article.php
<?php

namespace Adshares\CmsBundle\Entity;

use Adshares\CmsBundle\Repository\ArticleRepository;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(ArticleRepository::class)]
#[Gedmo\SoftDeleteable(fieldName: "deletedAt", timeAware: false, hardDelete: true)]
#[Gedmo\Loggable]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: "integer")]
    private int $id;

    #[ORM\Column(type: "string", length: 16, enumType: ArticleType::class, options: ["default" => ArticleType::Article])]
    private ArticleType $type = ArticleType::Article;

    #[ORM\Column(type: "json")]
    private array $tags = [];

    #[ORM\Column(type: "datetime", nullable: true)]
    private ?DateTimeInterface $startAt = null;

    #[ORM\Column(type: "datetime", nullable: true)]
    private ?DateTimeInterface $endAt = null;

    #[ORM\ManyToOne(targetEntity: User::class, fetch: 'EAGER')]
    private User $author;

    #[ORM\Column(type: "string", length: 128)]
    private string $name;

    #[ORM\Column(type: "string", length: 1024)]
    private string $title;

    #[ORM\Column(type: "text")]
    #[Gedmo\Versioned]
    private string $content;

    #[ORM\Column(type: "string", length: 64, nullable: true)]
    private ?string $image = null;

    #[ORM\Column(type: "string", length: 16, nullable: true)]
    #[Assert\Regex('/^[^#&?]{11}$/')]
    private ?string $video = null;

    #[ORM\Column(type: "integer", nullable: true)]
    private ?int $no = null;

    #[ORM\Column(type: "datetime")]
    #[Gedmo\Timestampable(on: "create")]
    private DateTimeInterface $createdAt;

    #[ORM\Column(type: "datetime")]
    #[Gedmo\Timestampable(on: "update")]
    private DateTimeInterface $updatedAt;

    #[ORM\Column(type: "datetime", nullable: true)]
    private ?DateTimeInterface $deletedAt = null;

    public function getId(): int
    {
        return $this->id;
    }

    public function getType(): ArticleType
    {
        return $this->type;
    }

    public function setType(ArticleType $type): Article
    {
        $this->type = $type;
        return $this;
    }

    /**
     * @return ArticleTag[]
     */
    public function getTags(): array
    {
        return array_map(fn(string $tag) => ArticleTag::from($tag), $this->tags);
    }

    public function getTag(): ?ArticleTag
    {
        $tags = $this->getTags();
        return reset($tags);
    }

    /**
     * @param ArticleTag[] $tags
     */
    public function setTags(array $tags): Article
    {
        $this->tags = array_map(fn(ArticleTag $tag) => $tag->value, $tags);
        return $this;
    }

    public function getStartAt(): ?DateTimeInterface
    {
        return $this->startAt;
    }

    public function setStartAt(?DateTimeInterface $startAt): Article
    {
        $this->startAt = $startAt;
        return $this;
    }

    public function getEndAt(): ?DateTimeInterface
    {
        return $this->endAt;
    }

    public function setEndAt(?DateTimeInterface $endAt): Article
    {
        $this->endAt = $endAt;
        return $this;
    }

    public function getAuthor(): User
    {
        return $this->author;
    }

    public function setAuthor(User $author): Article
    {
        $this->author = $author;
        return $this;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): Article
    {
        $this->name = $name;
        return $this;
    }

    public function getTitle(): string
    {
        return $this->title;
    }

    public function setTitle(string $title): Article
    {
        $this->title = $title;
        return $this;
    }

    public function getContent(): string
    {
        return $this->content;
    }

    public function setContent(string $content): Article
    {
        $this->content = $content;
        return $this;
    }

    public function getShortForm($length = 256): string
    {
        $content = $this->content;
        $matches = [];
        if (preg_match('/<p[^>]*>(.+)<\/p>/i', $this->content, $matches)) {
            $content = $matches[1];
        }
        $content = strip_tags($content);
        $suffix = strlen($content) > $length ? '…' : '';
        return substr($content, 0, $length) . $suffix;
    }

    public function getReadingLength(): int
    {
        return ceil(str_word_count(strip_tags($this->title . $this->content)) / 250);
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): Article
    {
        $this->image = $image;
        return $this;
    }

    public function getVideo(): ?string
    {
        return $this->video;
    }

    public function setVideo(?string $video): Article
    {
        $this->video = $video;
        return $this;
    }

    public function getNo(): ?int
    {
        return $this->no;
    }

    public function setNo(?int $no): Article
    {
        $this->no = $no;
        return $this;
    }

    public function getCreatedAt(): DateTimeInterface
    {
        return $this->createdAt;
    }

    public function getUpdatedAt(): DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function getDeletedAt(): ?DateTimeInterface
    {
        return $this->deletedAt;
    }

    public function restore(): self
    {
        $this->deletedAt = null;
        return $this;
    }

    public function getSchemaOrgType(): string
    {
        if (in_array(ArticleTag::Announcement, $this->getTags())) {
            return 'NewsArticle';
        }
        if (in_array($this->type, [
                ArticleType::Article,
                ArticleType::Event,
            ]
        )) {
            return 'SocialMediaPosting';
        }
        if (in_array($this->type, [
                ArticleType::Tutorial,
                ArticleType::General,
                ArticleType::Short,
                ArticleType::Term,
                ArticleType::FAQ
            ]
        )) {
            return 'TechArticle';
        }
        return 'Article';
    }
}

src/Entity/ArticleType.php
<?php

namespace Adshares\CmsBundle\Entity;

enum ArticleType: string
{
    case Article = 'article';
    case Event = 'event';
    case FAQ = 'faq';
    case General = 'general';
    case Notice = 'notice';
    case Short = 'short';
    case Term = 'term';
    case Tutorial = 'tutorial';

    public function slug(): string
    {
        return match ($this) {
            self::Article => 'articles',
            self::Event => 'events',
            self::Notice => 'notices',
            self::Short => 'shorts',
            self::Term => 'terms',
            self::Tutorial => 'tutorials',
            default => $this->value,
        };
    }

    public static function tryFromSlug(string $slug): ?ArticleType
    {
        return match ($slug) {
            'articles' => self::Article,
            'events' => self::Event,
            'notices' => self::Notice,
            'shorts' => self::Short,
            'terms' => self::Term,
            'tutorials' => self::Tutorial,
            default => self::tryFrom($slug),
        };
    }
}

src/Form/Type/ArticleType.php
<?php

namespace Adshares\CmsBundle\Form\Type;

use Adshares\CmsBundle\Entity\ArticleTag;
use Adshares\CmsBundle\Entity\ArticleType as ArticleTypeEnum;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\EnumType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $isArticle = ArticleTypeEnum::Article === $options['data']->getType();
        $isFAQ = ArticleTypeEnum::FAQ === $options['data']->getType();

        $builder
            ->add('type', EnumType::class, [
                'class' => ArticleTypeEnum::class,
            ])
            ->add('tags', EnumType::class, [
                'multiple' => true,
                'expanded' => true,
                'class' => ArticleTag::class,
                'label_attr' => ['class' => 'pt-0'],
            ])
            ->add('startAt', DateTimeType::class, [
                'widget' => 'single_text',
                'with_seconds' => true,
                'disabled' => $isFAQ,
            ])
            ->add('endAt', DateTimeType::class, [
                'required' => false,
                'widget' => 'single_text',
                'with_seconds' => true,
                'disabled' => $isArticle || $isFAQ,
            ])
            ->add('title', TextType::class)
            ->add('name', TextType::class, [
                'label' => 'Name (URL)',
            ])
            ->add('no', IntegerType::class, [
                'disabled' => $isArticle,
                'label' => 'No.'
            ])
            ->add('image', FileType::class, [
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/gif',
                            'image/jpeg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid image',
                    ])
                ],
            ])
            ->add('video', TextType::class, [
                'required' => false,
            ])
            ->add('content', TextareaType::class, [
                'attr' => ['rows' => 40],
            ])
            ->add('save', SubmitType::class, ['label' => $options['edit_mode'] ? 'Save article' : 'Create article']);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'csrf_protection' => true,
            'edit_mode' => false,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace Adshares\CmsBundle\Controller;

use Adshares\CmsBundle\Cms\FileUploader;
use Adshares\CmsBundle\Entity\Article;
use Adshares\CmsBundle\Entity\ArticleTag;
use Adshares\CmsBundle\Entity\ArticleType as ArticleTypeEnum;
use Adshares\CmsBundle\Entity\User;
use Adshares\CmsBundle\Form\Type\ArticleType;
use Adshares\CmsBundle\Repository\ArticleRepository;
use DateTimeImmutable;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Security\Core\User\UserInterface;

class ArticleController extends ViewController
{
    const ITEMS_PER_PAGE = 10;

    public function index(Request $request, ArticleRepository $repository): Response
    {
        $query = $request->get('query', '');
        $type = ArticleTypeEnum::tryFrom($request->get('type', null));
        $tag = ArticleTag::tryFrom($request->get('tag', null));
        $page = max(1, (int)$request->get('page', 1));

        $articles = $repository->findByQuery(
            $query,
            [$type],
            [$tag],
            [],
            false,
            self::ITEMS_PER_PAGE,
            ($page - 1) * self::ITEMS_PER_PAGE
        );

        return $this->render('@AdsharesCms/article/articles.html.twig', [
            'searchQuery' => $query,
            'articles' => $articles,
            'currentPage' => $page,
            'pages' => max(1, ceil($articles->count() / self::ITEMS_PER_PAGE)),
            'types' => ArticleTypeEnum::cases(),
            'selectedType' => $type,
        ]);
    }

    public function show(int $id, Request $request, ArticleRepository $repository): Response
    {
        if (null === $article = $repository->find($id)) {
            throw new NotFoundHttpException(sprintf('Cannot find article "%s"', $id));
        }

        return $this->render('@AdsharesCms/article/article.html.twig', [
            'article' => $article,
        ]);
    }

    public function form(
        ?int $id,
        Request $request,
        ArticleRepository $repository,
        FileUploader $fileUploader,
        UserInterface $user
    ): Response {
        $editMode = false;
        if (null !== $id) {
            if (null === $article = $repository->find($id)) {
                throw new NotFoundHttpException(sprintf('Cannot find article "%s"', $id));
            }
            $editMode = true;
        } else {
            $article = new Article();
            $article->setStartAt(new DateTimeImmutable());
            if ($user instanceof User) {
                $article->setAuthor($user);
            }
        }

        $form = $this->createForm(ArticleType::class, $article, [
            'edit_mode' => $editMode
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $repository->add($article, true);

            $file = $form['image']->getData();
            if (null !== $file) {
                $article->setImage($fileUploader->uploadArticle($file));
                $repository->add($article, true);
            }

            return $this->redirectToRoute('cms_article', ['id' => $article->getId(), 'name' => $article->getName()]);
        }

        return $this->renderForm('@AdsharesCms/article/article-editor.html.twig', [
            'form' => $form,
        ]);
    }

    public function delete(int $id, ArticleRepository $repository): Response
    {
        if (null === $article = $repository->find($id)) {
            throw new NotFoundHttpException(sprintf('Cannot find article "%s"', $id));
        }
        $repository->remove($article, true);
        return new Response('', 204);
    }
}

src/Resources/views/article/article-editor.html.twig
{% extends '@AdsharesCms/cms/_base.html.twig' %}

{% block body %}
    {% include '@AdsharesCms/article/form.html.twig' %}
{% endblock %}

src/Resources/views/article/article.html.twig
{% extends '@AdsharesCms/cms/_base.html.twig' %}

{% block body %}
    {% include '@AdsharesCms/article/details.html.twig' %}
{% endblock %}

src/Resources/views/article/articles.html.twig
{% extends '@AdsharesCms/cms/_base.html.twig' %}

{% block body %}
    {% include '@AdsharesCms/article/list.html.twig' %}
{% endblock %}

src/Resources/views/article/details.html.twig
<section class="cms-article-details">
    <div class="cms-article w-75 mx-auto">
        <div class="d-flex justify-content-between">
            <div>
                <strong>{{ article.author.name }}</strong>
                <span class="ms-3">{{ article.createdAt | date }}</span>
            </div>
            <div>
                Updated at: <span>{{ article.updatedAt | date }}</span>
            </div>
        </div>
        <div class="d-flex justify-content-between">
            <div>
                <strong>{{ article.type.name }}</strong>
                {% if article.tags is not empty %}|{% endif %}
                {% for tag in article.tags %}
                    <em>{{ tag.label }}</em>{% if not loop.last %},{% endif %}
                {% endfor %}
                | {{ article.readingLength }} min read
            </div>
            <div>
                {% if article.startAt %}
                    Start at: <u>{{ article.startAt | date }}</u>
                {% endif %}
                {% if article.endAt %}
                    | End at: <u>{{ article.endAt | date }}</u>
                {% endif %}
            </div>
        </div>
        <div class="d-flex justify-content-between mt-3">
            <a class="btn btn-sm btn-secondary me-2" href="{{ path('cms_article_edit', { id: article.id, ref: app.request.requesturi }) }}"><i class="bi bi-pencil"></i>Edit</a>
            <button type="submit" class="cms-delete-button btn btn-sm btn-danger ms-2"
                    data-action="{{ path('cms_article_delete', { id: article.id }) }}" data-ref="{{ path('cms_articles') }}">
                <i class="bi bi-x-square"></i> Delete
            </button>
        </div>
        <hr />
        <h2 class="mt-3">{{ article.title | raw }}</h2>
        {% if article.image %}
            <div class="my-5">
                <img class="w-100" src="{{ article.image }}" alt="{{ article.title }}" />
            </div>
        {% endif %}
        {% if article.video %}
            <div class="my-5 ratio ratio-16x9">
                <iframe src="https://www.youtube.com/embed/{{ article.video }}" title="YouTube video player" allow=" encrypted-media" allowfullscreen></iframe>
            </div>
        {% endif %}
        <div>
            {{ article.content | raw }}
        </div>
    </div>
</section>

src/Resources/views/article/form.html.twig
<section class="cms-article-form">
    {{ form_start(form) }}
    <div class="row align-items-start">
        <div class="col-10">
            <div class="row">
                <div class="col-2">
                    {{ form_row(form.type) }}
                </div>
                <div class="col-2">
                    {{ form_row(form.no) }}
                </div>
                <div class="col">
                    {{ form_row(form.startAt) }}
                </div>
                <div class="col">
                    {{ form_row(form.endAt) }}
                </div>
            </div>
            <div class="row">
                <div class="col">
                    {{ form_row(form.title) }}
                </div>
            </div>
            <div class="row">
                <div class="col">
                    {{ form_row(form.name) }}
                </div>
            </div>
            <div class="row">
                <div class="col">
                    {{ form_row(form.image) }}
                </div>
                <div class="col">
                    {{ form_row(form.video) }}
                </div>
            </div>
        </div>
        <div class="col">
            {{ form_row(form.tags) }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            {{ form_row(form.content) }}
        </div>
    </div>
    <div class="m-3">
        {{ form_errors(form) }}
    </div>
    <div class="m-3">
        {{ form_row(form.save) }}
    </div>
    {{ form_end(form) }}
</section>

src/Resources/views/article/list.html.twig
<section class="cms-article-list">
    <form method="get" action="{{ path('cms_articles') }}" class="text-center mb-4">
        <input type="hidden" name="_ref" value="{{ app.request.query.get('_ref') }}">
        <div class="d-flex justify-content-between">
            <div>
                <a class="btn btn-sm btn-primary" href="{{ path('cms_article_new', { ref: app.request.requesturi }) }}"><i class="bi bi-plus-square"></i> Create new article</a>
            </div>
            <div class="row g-3 align-items-center justify-content-end w-75">
                <div class="col-auto">
                    <select name="type" class="form-select form-select-sm">
                        <option value="" {% if not selectedType %}selected{% endif %}>All types</option>
                        {% for type in types %}
                            <option value="{{ type.value }}" {% if selectedType == type %}selected{% endif %}>{{ type.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-auto">
                    <input type="text" id="cmsArticlesSearch" class="form-control form-control-sm" name="query" value="{{ searchQuery }}">
                </div>
                <div class="col-auto">
                    <button class="btn btn-secondary btn-sm" type="submit"><i class="bi bi-search"></i></button>
                </div>
            </div>
        </div>
    </form>
    <hr />

    <div class="cms-articles">
        {% set empty = true %}
        {% for article in articles %}
            {% set empty = false %}
            <div class="row cms-article">
                <div class="col-8 d-flex flex-column justify-content-between">
                    <div>
                        <div class="d-flex justify-content-between align-items-center">
                            <div>
                                <strong>{{ article.author.name }}</strong>
                                <span class="ms-3">{{ article.createdAt | date }}</span>
                            </div>
                            <div>
                                <a class="btn btn-sm btn-secondary" href="{{ path('cms_article_edit', { id: article.id, ref: app.request.requesturi }) }}" title="Edit article">Edit</a>
                            </div>
                        </div>
                        <a href="{{ path('cms_article', { id: article.id, name: article.name, ref: app.request.requesturi }) }}" title="Article">
                            <h2 class="mt-3">{{ article.title | raw }}</h2>
                        </a>
                    </div>
                    <div class="d-flex justify-content-between">
                        <div>
                            <strong>{{ article.type.name }}</strong>
                            {% if article.tags is not empty %}|{% endif %}
                            {% for tag in article.tags %}
                                <a href="{{ path('cms_articles', { tag: tag.value, _ref: app.request.query.get('_ref') }) }}"><em>{{ tag.label }}</em></a>{% if not loop.last %},{% endif %}
                            {% endfor %}
                        </div>
                        <div>
                            {% if article.startAt %}
                                Start at: <u>{{ article.startAt | date }}</u>
                            {% endif %}
                            {% if article.endAt %}
                            | End at: <u>{{ article.endAt | date }}</u>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-4">
                    {% if article.image %}
                        <div class="ratio ratio-21x9">
                            {{ img(article.image, 350, 150, article.title) }}
                        </div>
                    {% endif %}
                </div>
            </div>
            <hr />
        {% endfor %}
        {% if empty %}
            <h2 class="text-center"><span class="badge bg-primary">Nothing found</span></h2>
        {% endif %}
    </div>

    <nav>
        <ul class="pagination justify-content-center">
            {% for i in 1..pages %}
                <li class="page-item {% if currentPage == i %}active{% endif %}">
                    {% if currentPage == i %}
                        <span class="page-link">{{ i }}</span>
                    {% else %}
                        <a class="page-link" href="{{ path('cms_articles', app.request.query.all | merge({ page: i })) }}">{{ i }}</a>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </nav>
</section>